service:
  name: say-hello
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: src/lambda.hello
    events:
      - http:
          method: get
          path: hello
  helloExpress:
    handler: src/lambdaExpress.handler
    events:
      - http:
          method: get
          path: hello/express
